GET http://localhost:7000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJEaWtzZmFzYW5kaSIsImVtYWlsIjoiZW1haWwxQGVtYWlsLmNvbSIsImlhdCI6MTY4NTQ0ODE0OSwiZXhwIjoxNjg1NDQ4MTg5fQ.uL1ypHMJUhnPr9H92a_hJYYNlhsjKn_iF_d86X5akOc


###
POST http://localhost:7000/users
Content-Type: application/json


{
    "name": "Diksfasandi",
    "email": "email1@email.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:7000/login
Content-Type: application/json

{
    "email": "email1@email.com",
    "password": "123456"
}

###
GET http://localhost:7000/token
###
DELETE  http://localhost:7000/logout
